### ISSUE TITLE
dependency converted to es6 without breaking change

### ISSUE THREAD

**Issue by marthakelly** [rtsao/unitest#13]
hey rtsao!

looks like electron-prebuilt uses electron-download which recently converted to es6 without a breaking change. unfortunately our ancient version of node prevents this from running the es6 postinstall script for electron-prebuilt. As you can imagine, this is b0rking all my installs with unitest as a dependency.

Issue for electron-prebuilt was reported here: https://github.com/electron-userland/electron-prebuilt/issues/190

Hopefully electron-download will fix the error, or electron-prebuilt will pin the version.

**Comment by rtsao** [comment]
This PR https://github.com/rtsao/unitest/pull/14 adds a shrinkwrap for electron-download@2.1.2 which fixes the problem.

**Comment by rtsao** [comment]
Released as `0.12.0`

**Comment by rtsao** [comment]
Although tests passed on Travis for #14, apparently I needed to nest the `elecron-download` dependency under `electron-prebuilt` in the shrinkwrap when actually installing `unitest` as a package, which is now fixed in `0.12.1`.

**Comment by marthakelly** [comment]
you're the best!

**Comment by kgryte** [comment]
@rtsao Apparently `electron-download` has been reverted to a pre-existing version (`2.1.2`), as noted here https://github.com/electron-userland/electron-prebuilt/issues/190 .
